name: channelvit
channels:
  - https://aws-ml-conda-ec2.s3.us-west-2.amazonaws.com
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.2=hd590300_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.9.17=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.1.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - aiobotocore==2.4.2
      - aiohttp==3.8.5
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - albumentations==1.3.1
      - annotated-types==0.5.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - arrow==1.2.3
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - blessed==1.20.0
      - boto3==1.24.59
      - botocore==1.27.59
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cmake==3.27.2
      - cramjam==2.7.0
      - croniter==1.4.1
      - dateutils==0.6.12
      - deepdiff==6.3.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.3
      - fastapi==0.101.1
      - fastparquet==2023.7.0
      - filelock==3.12.2
      - frozenlist==1.4.0
      - fsspec==2022.11.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - h11==0.14.0
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.31.1
      - inquirer==3.1.3
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - lazy-loader==0.3
      - lightning==2.0.7
      - lightning-cloud==0.5.37
      - lightning-utilities==0.9.0
      - lit==16.0.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - networkx==3.1
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - opencv-python-headless==4.8.0.76
      - ordered-set==4.1.0
      - packaging==23.1
      - pandas==2.0.3
      - pathtools==0.1.2
      - pillow==10.0.0
      - protobuf==4.24.1
      - psutil==5.9.5
      - pyarrow==13.0.0
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - pygments==2.16.1
      - pyjwt==2.8.0
      - python-dateutil==2.8.2
      - python-editor==1.0.4
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.7
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - qudida==0.0.4
      - readchar==4.0.5
      - requests==2.31.0
      - rich==13.5.2
      - s3fs==2022.11.0
      - s3transfer==0.6.2
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - starlette==0.27.0
      - starsessions==1.3.0
      - sympy==1.12
      - threadpoolctl==3.2.0
      - tifffile==2023.8.12
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchmetrics==1.1.0
      - torchvision==0.15.2
      - tqdm==4.66.1
      - traitlets==5.9.0
      - triton==2.0.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==1.26.16
      - uvicorn==0.23.2
      - wandb==0.15.8
      - wcwidth==0.2.6
      - websocket-client==1.6.2
      - websockets==11.0.3
      - wrapt==1.15.0
      - yarl==1.9.2
      - timm==0.5.4
