# Configurations for the data transformations
name: CamelyonAugmentationDino
args:
  global_crops_scale:
    - 0.4
    - 1.0
    # Scale range of the cropped image before resizing, relatively to the origin image.
    # Used for large global view cropping. When disabling multi-crop
    # (--local_crops_number 0), we recommand using a wider range of scale
    # ("--global_crops_scale 0.14 1." for example)
  local_crops_number: 8
    # Number of small local views to generate. Set this parameter to 0 to disable
    # multi-crop training.  When disabling multi-crop we recommend to use
    # "--global_crops_scale 0.14 1."
  local_crops_scale:
    - 0.05
    - 0.4
    # Scale range of the cropped image before resizing, relatively to the origin image.
    # Used for small local view cropping of multi-crop.
