# Configurations for the data transformations
name: So2SatAugmentation
args:
  channel_mask: []

normalization:
  mean:
    - -3.5912242e-05
    - -7.658551e-06
    - 5.937501e-05
    - 2.516598e-05
    - 0.044198506
    - 0.25761467
    - 0.0007556685
    - 0.0013503395
    - 0.12375654
    - 0.109277464
    - 0.101086065
    - 0.114239536
    - 0.15926327
    - 0.18147452
    - 0.17457514
    - 0.1950194
    - 0.15428114
    - 0.109052904
  std:
    - 0.17555329
    - 0.17556609
    - 0.4599934
    - 0.45599362
    - 2.855352
    - 8.322579
    - 2.44937
    - 1.464371
    - 0.0395863
    - 0.047778852
    - 0.066362865
    - 0.063593246
    - 0.07744504
    - 0.09099384
    - 0.09217117
    - 0.10162713
    - 0.09989747
    - 0.0877891
